##using linear regression libraries in pytorch

In [24]:
import torch.nn as nn
import numpy as np

In [25]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

Dataset and DataLoader

In [26]:
from torch.utils.data import TensorDataset

In [27]:
#Define dataset
train_ds = TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [28]:
from torch.utils.data import DataLoader

In [29]:
#define data loader
batch_size = 5
train_dl = DataLoader(train_ds , batch_size , shuffle=True)

In [30]:
for xb, yb in train_dl:
  print(xb)
  print(yb)


tensor([[ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [ 69.,  96.,  70.]])
tensor([[ 82., 100.],
        [118., 134.],
        [ 22.,  37.],
        [ 56.,  70.],
        [103., 119.]])
tensor([[ 73.,  66.,  44.],
        [ 91.,  87.,  65.],
        [ 87., 134.,  58.],
        [103.,  43.,  36.],
        [ 68.,  96.,  71.]])
tensor([[ 57.,  69.],
        [ 80., 102.],
        [119., 133.],
        [ 20.,  38.],
        [104., 118.]])
tensor([[ 88., 134.,  59.],
        [ 68.,  97.,  70.],
        [101.,  44.,  37.],
        [ 74.,  66.,  43.],
        [ 91.,  88.,  64.]])
tensor([[118., 132.],
        [102., 120.],
        [ 21.,  38.],
        [ 57.,  69.],
        [ 81., 101.]])


##nn.Linear
Instead of initializing the weights and biases manually , we can define the model using the nn.Linear class from Pytorch

In [31]:
model = nn.Linear(3,2) #(number of inputs features , number of output classes)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.4183,  0.3219,  0.2654],
        [-0.2315,  0.4969, -0.1195]], requires_grad=True)
Parameter containing:
tensor([ 0.3499, -0.3423], requires_grad=True)


In [32]:
preds = model(inputs)
preds

tensor([[63.8660, 10.9128],
        [83.7292, 14.6709],
        [95.2698, 39.1709],
        [66.6791, -7.0076],
        [78.6942, 23.0209],
        [63.9625, 10.1844],
        [83.6728, 14.0545],
        [95.9535, 38.8199],
        [66.5827, -6.2793],
        [78.5414, 23.1328],
        [63.8096, 10.2963],
        [83.8257, 13.9426],
        [95.3262, 39.7873],
        [66.8320, -7.1195],
        [78.5978, 23.7492]], grad_fn=<AddmmBackward0>)

Loss Function 
Instead of defining a loss function as above , we use inbuilt loss function mse_loss

In [33]:
#import nn.functional 
import torch.nn.functional as F

In [34]:
#define loss function
loss_fn = F.mse_loss

In [35]:
loss = loss_fn(model(inputs) , targets)
print(loss)

tensor(3418.6433, grad_fn=<MseLossBackward0>)


OPTIMIZER

In [37]:
opt = torch.optim.SGD(model.parameters() , lr = 1e-5) 

##Model Training

In [38]:
def fit(num_epochs , model, loss_fn,opt):
  for epoch in range(num_epochs):
    for xb,yb in train_dl:
      pred=model(xb)
      loss = loss_fn(pred,yb)
      loss.backward()
      opt.step()
      #reset gradients to zero 
      opt.zero_grad()
    
    if(epoch+1) %10==0:
      print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1 , num_epochs ,loss.item() ))



In [40]:
fit(1000 , model , loss_fn , opt)

Epoch [10/1000], Loss: 15.0198
Epoch [20/1000], Loss: 20.4537
Epoch [30/1000], Loss: 21.2881
Epoch [40/1000], Loss: 21.2027
Epoch [50/1000], Loss: 19.5040
Epoch [60/1000], Loss: 16.7030
Epoch [70/1000], Loss: 10.8896
Epoch [80/1000], Loss: 23.1307
Epoch [90/1000], Loss: 7.0232
Epoch [100/1000], Loss: 20.3429
Epoch [110/1000], Loss: 12.0630
Epoch [120/1000], Loss: 16.9124
Epoch [130/1000], Loss: 7.6327
Epoch [140/1000], Loss: 13.7099
Epoch [150/1000], Loss: 12.6326
Epoch [160/1000], Loss: 14.0451
Epoch [170/1000], Loss: 8.1761
Epoch [180/1000], Loss: 11.7477
Epoch [190/1000], Loss: 6.3989
Epoch [200/1000], Loss: 9.7828
Epoch [210/1000], Loss: 12.2607
Epoch [220/1000], Loss: 4.7411
Epoch [230/1000], Loss: 5.7595
Epoch [240/1000], Loss: 7.8975
Epoch [250/1000], Loss: 6.0619
Epoch [260/1000], Loss: 4.7759
Epoch [270/1000], Loss: 5.0066
Epoch [280/1000], Loss: 3.1849
Epoch [290/1000], Loss: 6.4584
Epoch [300/1000], Loss: 3.7351
Epoch [310/1000], Loss: 5.1700
Epoch [320/1000], Loss: 4.7352
E

In [41]:
preds = model(inputs)
preds

tensor([[ 56.9974,  70.4046],
        [ 81.8771, 100.4250],
        [118.3374, 133.3009],
        [ 20.8405,  37.9159],
        [101.6553, 118.1236],
        [ 55.7462,  69.3245],
        [ 81.7150, 100.4854],
        [118.6176, 133.8876],
        [ 22.0916,  38.9960],
        [102.7443, 119.2640],
        [ 56.8352,  70.4650],
        [ 80.6260,  99.3449],
        [118.4995, 133.2405],
        [ 19.7515,  36.7755],
        [102.9065, 119.2037]], grad_fn=<AddmmBackward0>)

In [42]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])